### ISSUE TITLE
myparts.lib missing

### ISSUE THREAD

**Issue by LFSaw** [madworm/Serial-Knob#1]
Hello,

I tried to extract the footprint for the ALPS encoder from this project, however, the myParts.lib is missing and the project does not open on my machine... (you set an absolute path to the library...)

**Comment by madworm** [comment]
The schematic symbols area cached in "Serial-Knob-cache.lib", so it should work.

If you're just after the footprint, try this: https://github.com/madworm/Rotary-Encoders.pretty
